// @generated by protoc-gen-connect-es v1.6.1
// @generated from file filesystem.proto (package fs, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetImageRequest, GetImageResponse, ListFilesRequest, ListFilesResponse } from "./filesystem_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definition
 *
 * @generated from service fs.FileSystem
 */
export const FileSystem = {
  typeName: "fs.FileSystem",
  methods: {
    /**
     * @generated from rpc fs.FileSystem.ListFiles
     */
    listFiles: {
      name: "ListFiles",
      I: ListFilesRequest,
      O: ListFilesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc fs.FileSystem.GetImage
     */
    getImage: {
      name: "GetImage",
      I: GetImageRequest,
      O: GetImageResponse,
      kind: MethodKind.Unary,
    },
  }
};

