// @generated by protoc-gen-es v2.5.2
// @generated from file filesystem.proto (package fs, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file filesystem.proto.
 */
export declare const file_filesystem: GenFile;

/**
 * Request a list of files
 *
 * @generated from message fs.ListFilesRequest
 */
export declare type ListFilesRequest = Message<"fs.ListFilesRequest"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;
};

/**
 * Describes the message fs.ListFilesRequest.
 * Use `create(ListFilesRequestSchema)` to create a new message.
 */
export declare const ListFilesRequestSchema: GenMessage<ListFilesRequest>;

/**
 * Response with filenames
 *
 * @generated from message fs.ListFilesResponse
 */
export declare type ListFilesResponse = Message<"fs.ListFilesResponse"> & {
  /**
   * @generated from field: repeated string filenames = 1;
   */
  filenames: string[];
};

/**
 * Describes the message fs.ListFilesResponse.
 * Use `create(ListFilesResponseSchema)` to create a new message.
 */
export declare const ListFilesResponseSchema: GenMessage<ListFilesResponse>;

/**
 * Request image data
 *
 * @generated from message fs.GetImageRequest
 */
export declare type GetImageRequest = Message<"fs.GetImageRequest"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: uint32 width = 2;
   */
  width: number;
};

/**
 * Describes the message fs.GetImageRequest.
 * Use `create(GetImageRequestSchema)` to create a new message.
 */
export declare const GetImageRequestSchema: GenMessage<GetImageRequest>;

/**
 * Binary image data
 *
 * @generated from message fs.GetImageResponse
 */
export declare type GetImageResponse = Message<"fs.GetImageResponse"> & {
  /**
   * @generated from field: bytes image_data = 1;
   */
  imageData: Uint8Array;
};

/**
 * Describes the message fs.GetImageResponse.
 * Use `create(GetImageResponseSchema)` to create a new message.
 */
export declare const GetImageResponseSchema: GenMessage<GetImageResponse>;

/**
 * Service definition
 *
 * @generated from service fs.FileSystem
 */
export declare const FileSystem: GenService<{
  /**
   * @generated from rpc fs.FileSystem.ListFiles
   */
  listFiles: {
    methodKind: "unary";
    input: typeof ListFilesRequestSchema;
    output: typeof ListFilesResponseSchema;
  },
  /**
   * @generated from rpc fs.FileSystem.GetImage
   */
  getImage: {
    methodKind: "unary";
    input: typeof GetImageRequestSchema;
    output: typeof GetImageResponseSchema;
  },
}>;

