// @generated by protoc-gen-es v2.5.2
// @generated from file filesystem.proto (package fs, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file filesystem.proto.
 */
export const file_filesystem = /*@__PURE__*/
  fileDesc("ChBmaWxlc3lzdGVtLnByb3RvEgJmcyIgChBMaXN0RmlsZXNSZXF1ZXN0EgwKBHBhdGgYASABKAkiJgoRTGlzdEZpbGVzUmVzcG9uc2USEQoJZmlsZW5hbWVzGAEgAygJIi4KD0dldEltYWdlUmVxdWVzdBIMCgRwYXRoGAEgASgJEg0KBXdpZHRoGAIgASgNIiYKEEdldEltYWdlUmVzcG9uc2USEgoKaW1hZ2VfZGF0YRgBIAEoDDJ9CgpGaWxlU3lzdGVtEjgKCUxpc3RGaWxlcxIULmZzLkxpc3RGaWxlc1JlcXVlc3QaFS5mcy5MaXN0RmlsZXNSZXNwb25zZRI1CghHZXRJbWFnZRITLmZzLkdldEltYWdlUmVxdWVzdBoULmZzLkdldEltYWdlUmVzcG9uc2VCCFoGLi9mc3BiYgZwcm90bzM");

/**
 * Describes the message fs.ListFilesRequest.
 * Use `create(ListFilesRequestSchema)` to create a new message.
 */
export const ListFilesRequestSchema = /*@__PURE__*/
  messageDesc(file_filesystem, 0);

/**
 * Describes the message fs.ListFilesResponse.
 * Use `create(ListFilesResponseSchema)` to create a new message.
 */
export const ListFilesResponseSchema = /*@__PURE__*/
  messageDesc(file_filesystem, 1);

/**
 * Describes the message fs.GetImageRequest.
 * Use `create(GetImageRequestSchema)` to create a new message.
 */
export const GetImageRequestSchema = /*@__PURE__*/
  messageDesc(file_filesystem, 2);

/**
 * Describes the message fs.GetImageResponse.
 * Use `create(GetImageResponseSchema)` to create a new message.
 */
export const GetImageResponseSchema = /*@__PURE__*/
  messageDesc(file_filesystem, 3);

/**
 * Service definition
 *
 * @generated from service fs.FileSystem
 */
export const FileSystem = /*@__PURE__*/
  serviceDesc(file_filesystem, 0);

