// @generated by protoc-gen-es v1.10.1
// @generated from file filesystem.proto (package fs, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * File information
 *
 * @generated from message fs.FileInfo
 */
export declare class FileInfo extends Message<FileInfo> {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * @generated from field: bool is_dir = 2;
   */
  isDir: boolean;

  constructor(data?: PartialMessage<FileInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "fs.FileInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FileInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FileInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FileInfo;

  static equals(a: FileInfo | PlainMessage<FileInfo> | undefined, b: FileInfo | PlainMessage<FileInfo> | undefined): boolean;
}

/**
 * Request a list of files
 *
 * @generated from message fs.ListFilesRequest
 */
export declare class ListFilesRequest extends Message<ListFilesRequest> {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  constructor(data?: PartialMessage<ListFilesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "fs.ListFilesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListFilesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListFilesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListFilesRequest;

  static equals(a: ListFilesRequest | PlainMessage<ListFilesRequest> | undefined, b: ListFilesRequest | PlainMessage<ListFilesRequest> | undefined): boolean;
}

/**
 * Response with file information
 *
 * @generated from message fs.ListFilesResponse
 */
export declare class ListFilesResponse extends Message<ListFilesResponse> {
  /**
   * @generated from field: repeated fs.FileInfo files = 1;
   */
  files: FileInfo[];

  constructor(data?: PartialMessage<ListFilesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "fs.ListFilesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListFilesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListFilesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListFilesResponse;

  static equals(a: ListFilesResponse | PlainMessage<ListFilesResponse> | undefined, b: ListFilesResponse | PlainMessage<ListFilesResponse> | undefined): boolean;
}

/**
 * Request image data
 *
 * @generated from message fs.GetImageRequest
 */
export declare class GetImageRequest extends Message<GetImageRequest> {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: uint32 width = 2;
   */
  width: number;

  constructor(data?: PartialMessage<GetImageRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "fs.GetImageRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetImageRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetImageRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetImageRequest;

  static equals(a: GetImageRequest | PlainMessage<GetImageRequest> | undefined, b: GetImageRequest | PlainMessage<GetImageRequest> | undefined): boolean;
}

/**
 * Binary image data
 *
 * @generated from message fs.GetImageResponse
 */
export declare class GetImageResponse extends Message<GetImageResponse> {
  /**
   * @generated from field: bytes image_data = 1;
   */
  imageData: Uint8Array;

  constructor(data?: PartialMessage<GetImageResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "fs.GetImageResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetImageResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetImageResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetImageResponse;

  static equals(a: GetImageResponse | PlainMessage<GetImageResponse> | undefined, b: GetImageResponse | PlainMessage<GetImageResponse> | undefined): boolean;
}

